### PR TITLE
Fixed compilation error after upgrading solr-solrj from 8.11.0 to 9.1.0

### PR DESCRIPTION
**Pull request by patsonluk**
## Description
There are several compilation errors after the upgrade enforced by Synk:
https://github.com/fullstorydev/solr-bench/pull/57

## Cause/Solution
1. Common IO Utils are now runtime dependency. Fix : simply replace those calls with java standard lib functions
2. ZkStateReader/ZkClient no longer directly available from the `CloudSolrClient`. Fix: for simplicity we included the `org.apache.solr:solr-solrj-zookeeper:9.1.0` and `org.apache.zookeeper:zookeeper:3.8.0` ~as provided dependency~ (has to be compiled, as the runtime environment does not have it by default) and obtain the ZkStateReader/ZkClient from `CloudSolrClient.getClusterStateProvider` with class casting. We could have instantiate the SolrZkClient directly, but that would require exactly the same extra dependencies anyway, so let's just keep using the one from `CloudSolrClient`
3. Other misc changes such as CloudSolrClient$Builder signature change, deprecation of maxShard etc

### CODE REVIEW

**Comment by patsonluk** [comment]
Going to merge this one in as the current master cannot compile 😅

File: pom.xml [hunk 1]
```diff
@@ -34,6 +34,22 @@
...
+      </dependency>
+      <dependency>
+         <groupId>org.apache.zookeeper</groupId>
+         <artifactId>zookeeper</artifactId>
+         <version>3.8.0</version>
+      </dependency>
+      <dependency>
+         <groupId>org.eclipse.jetty</groupId>
+         <artifactId>jetty-client</artifactId>
+         <version>9.4.48.v20220622</version>
```
Comment (hiteshk25) [inline pom.xml:50]: any particular reason to stick with 9.4.48 version?

Comment (patsonluk) [reply pom.xml:50]: O I used the runtime dependency version of solrj 9.1.0 :) 
https://mvnrepository.com/artifact/org.apache.solr/solr-solrj/9.1.0
